### PR TITLE
build definition logic added + INT level tests

### PR DESCRIPTION
**Pull request by VaclavK**
let's have a conversation around INT tests

I have introduced the build definition long running  E2E test (it schedules build and waits for its completion)as we add more and more levels/artefacts the times would be too high and also I want to avoid constant tenant (and all sublayers) artefacts creation/deletion

at the very least we could move the tenant POST and DELETE to the fixture and the tests would simply check whatever they want to check

### CODE REVIEW

**Comment by djfr** [comment]
The POST on the build definition will do validation, if there's a problem with the definition itself we'll get notified after that call. We can't run builds to validate we're doing the right build definition at the actor level. At best we do some extra validation when we come up with the process to validate the build definition template, but we will worry about that further down the road!

**Comment by VaclavK** [comment]
@djfr following the conversation,  I have create the fixture US in the backlog and marked this test as dev level

**Comment by djfr** [comment]
Changed the C# Model for BuildDefinition to VstsBuildDefinition to avoid colliding with the VSTS SDK BuildDefinition. **I didn't re-create the migration! so right now it's broken**

I also added a kill switch that pools the VSTS build definition to be created, so that we avoid edge cases and the test stays there running *forever*.

**Comment by VaclavK** [comment]
@djfr yeah , will recreate the migration no problem... kill switch is a good idea
thanks for the review

**Pull request merged**
