### PR TITLE
Integration testing for forking

### PR DESCRIPTION
**Pull request by VaclavK**
we have to talk re LB for the Integration test

### CODE REVIEW

**Comment by djfr** [comment]
https://www.nuget.org/packages/Microsoft.TeamFoundationServer.Client/15.134.0-preview
https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/15.134.0-preview

Both have NS2.0 targets in them, and both work against VSTS

**Comment by VaclavK** [comment]
these do not support forking

**Comment by VaclavK** [comment]
@djfr updated now to use the git http client from the tfs client as discussed, feel free to review

looking at their oAuth support to see if I can remove the REST class to token endpoint

**Comment by VaclavK** [comment]
so MS' own sample does exacty what we do - https://github.com/Microsoft/vsts-auth-samples/blob/master/OAuthWebSample/OAuthWebSample/Controllers/OAuthController.cs

**Pull request merged**
